name: Build microsocks for Android (aarch64)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout microsocks
      uses: actions/checkout@v4
      with:
        repository: rofl0r/microsocks
        path: microsocks

    - name: Set up Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25c

    - name: Build microsocks (aarch64)
      run: |
        export TOOLCHAIN=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64
        export TARGET=aarch64-linux-android
        export API=21

        export CC=$TOOLCHAIN/bin/${TARGET}${API}-clang
        export AR=$TOOLCHAIN/bin/llvm-ar
        export STRIP=$TOOLCHAIN/bin/llvm-strip

        cd microsocks
        make clean
        make CC="$CC" AR="$AR"

        mkdir -p output
        $STRIP microsocks -o output/microsocks

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: microsocks-aarch64
        path: microsocks/output/microsocks
