name: Build microsocks for Android (aarch64)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout microsocks
      uses: actions/checkout@v4
      with:
        repository: rofl0r/microsocks
        path: microsocks

    - name: Set up Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r27

    - name: Patch Makefile and build
      run: |
        export TOOLCHAIN=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64
        export TARGET=aarch64-linux-android
        export API=21
        export CC=$TOOLCHAIN/bin/${TARGET}${API}-clang
        export STRIP=$TOOLCHAIN/bin/llvm-strip

        cd microsocks

        # Remove -lpthread which is not needed on Android
        sed -i 's/-lpthread//' Makefile

        make clean
        make CC="$CC"

        mkdir -p output
        $STRIP microsocks -o output/microsocks

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: microsocks-aarch64
        path: microsocks/output/microsocks
