name: Build redsocks for Android (aarch64)

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout redsocks
      uses: actions/checkout@v4
      with:
        repository: darkk/redsocks
        path: redsocks

    - name: Set up Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r27

    - name: Patch Makefile and build
      run: |
        export TOOLCHAIN=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64
        export TARGET=aarch64-linux-android
        export API=21
        export CC=$TOOLCHAIN/bin/${TARGET}${API}-clang
        export STRIP=$TOOLCHAIN/bin/llvm-strip
        export AR=$TOOLCHAIN/bin/llvm-ar

        cd redsocks

        # Remove -lpthread if present in Makefile
        sed -i 's/-lpthread//' Makefile

        make clean
        make CC="$CC" AR="$AR"

        mkdir -p output
        $STRIP redsocks -o output/redsocks

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: redsocks-aarch64
        path: red
