name: Build redsocks for Android (aarch64)

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout redsocks
      uses: actions/checkout@v4
      with:
        repository: darkk/redsocks
        path: redsocks

    - name: Checkout libevent
      uses: actions/checkout@v4
      with:
        repository: libevent/libevent
        ref: release-2.1.12-stable
        path: libevent

    - name: Set up Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r27

    - name: Build libevent for Android
      run: |
        export TOOLCHAIN=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64
        export TARGET=aarch64-linux-android
        export API=21
        export CC=$TOOLCHAIN/bin/${TARGET}${API}-clang
        export AR=$TOOLCHAIN/bin/llvm-ar
        export RANLIB=$TOOLCHAIN/bin/llvm-ranlib
        export HOST=${TARGET}

        cd libevent
        ./autogen.sh
        ./configure \
          --host=$HOST \
          --disable-shared \
          --enable-static \
          --disable-openssl \
          --prefix=$(pwd)/build \
          CC="$CC" AR="$AR" RANLIB="$RANLIB"

        make -j$(n
