name: Build Redsocks for Android AArch64

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build for Android AArch64
    runs-on: ubuntu-latest

    env:
      NDK_VERSION: "r27"
      API_LEVEL: "21"

    steps:
      - name: Checkout redsocks source
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip build-essential

      - name: Download Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-${NDK_VERSION}-linux.zip
          unzip -q android-ndk-${NDK_VERSION}-linux.zip
          echo "NDK path: $PWD/android-ndk-${NDK_VERSION}"

      - name: Set up environment variables
        run: |
          echo "TOOLCHAIN=$PWD/android-ndk-${NDK_VERSION}/toolchains/llvm/prebuilt/linux-x86_64" >> $GITHUB_ENV
          echo "TARGET=aarch64-linux-android" >> $GITHUB_ENV
          echo "CC=$PWD/android-ndk-${NDK_VERSION}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android${API_LEVEL}-clang" >> $GITHUB_ENV
          echo "AR=$PWD/android-ndk-${NDK_VERSION}/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar" >> $GITHUB_ENV
          echo "STRIP=$PWD/android-ndk-${NDK_VERSION}/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip" >> $GITHUB_ENV

      - name: Build redsocks
        run: |
          make clean
          make CC="$CC" AR="$AR" STRIP="$STRIP"

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: redsocks-aarch64
          path: redsocks
